"use client";

import React from "react";
import {
  PiAtomDuotone,
  PiBinaryDuotone,
  PiBinocularsDuotone,
  PiBirdDuotone,
  PiBlueprintDuotone,
  PiBombDuotone,
  PiBroomDuotone,
  PiHandHeartDuotone,
  PiThumbsUpDuotone,
  PiChatCircleTextDuotone,
  PiShareNetworkDuotone,
  PiBookmarkSimpleDuotone,
  PiCircuitryDuotone,
  PiCompassDuotone,
  PiCompassToolDuotone,
  PiCubeDuotone,
  PiLightningDuotone,
  PiCodeDuotone,
  PiPenNibDuotone,
  PiPaletteDuotone,
  PiCalculatorDuotone,
  PiUsersDuotone,
  PiHeartDuotone,
  PiTrophyDuotone,
  PiMedalDuotone,
  PiTargetDuotone,
  PiFireDuotone,
  PiSneakerDuotone,
  PiSparkleDuotone,
  PiFlagDuotone,
  PiFlagCheckeredDuotone,
  PiButterflyDuotone,
  PiGitBranchDuotone,
  PiGridNineDuotone,
  PiRocketLaunchDuotone,
  PiBugDuotone,
  PiFlaskDuotone,
  PiCakeDuotone,
  PiStarDuotone,
  PiHashDuotone,
  PiCrownDuotone,
  PiGraduationCapDuotone,
  PiBrainDuotone,
  PiUploadDuotone,
  PiShieldCheckDuotone,
  PiShieldStarDuotone,
  PiSquaresFourDuotone,
  PiEyeDuotone,
  PiFeatherDuotone,
  PiDnaDuotone,
  PiStackDuotone,
  PiLightbulbFilamentDuotone,
  PiNumberSquareTwoDuotone,
  PiPuzzlePieceDuotone,
  PiStrategyDuotone,
  PiTimerDuotone,
  PiTreeStructureDuotone,
} from "react-icons/pi";

export const PREMIUM_ICONS_MAP: Record<string, React.ElementType> = {
  atom: PiAtomDuotone,
  binary: PiBinaryDuotone,
  binoculars: PiBinocularsDuotone,
  bird: PiBirdDuotone,
  blueprint: PiBlueprintDuotone,
  bomb: PiBombDuotone,
  broom: PiBroomDuotone,
  hand_heart: PiHandHeartDuotone,
  thumbs_up: PiThumbsUpDuotone,
  message_circle: PiChatCircleTextDuotone,
  share_2: PiShareNetworkDuotone,
  bookmark: PiBookmarkSimpleDuotone,
  circuitry: PiCircuitryDuotone,
  compass: PiCompassDuotone,
  compass_tool: PiCompassToolDuotone,
  cube: PiCubeDuotone,
  zap: PiLightningDuotone,
  code_2: PiCodeDuotone,
  pen_tool: PiPenNibDuotone,
  palette: PiPaletteDuotone,
  calculator: PiCalculatorDuotone,
  users: PiUsersDuotone,
  heart: PiHeartDuotone,
  trophy: PiTrophyDuotone,
  award: PiMedalDuotone,
  target: PiTargetDuotone,
  flame: PiFireDuotone,
  footprints: PiSneakerDuotone,
  sparkles: PiSparkleDuotone,
  flag: PiFlagDuotone,
  flag_checkered: PiFlagCheckeredDuotone,
  butterfly: PiButterflyDuotone,
  git_branch: PiGitBranchDuotone,
  grid_nine: PiGridNineDuotone,
  rocket: PiRocketLaunchDuotone,
  bug: PiBugDuotone,
  flask: PiFlaskDuotone,
  cake: PiCakeDuotone,
  star: PiStarDuotone,
  hash: PiHashDuotone,
  crown: PiCrownDuotone,
  graduation_cap: PiGraduationCapDuotone,
  upload: PiUploadDuotone,
  medal: PiMedalDuotone,
  default: PiSparkleDuotone,
  // 游乐场游戏徽章
  shield: PiShieldCheckDuotone,
  shield_star: PiShieldStarDuotone,
  "grid_3x3": PiSquaresFourDuotone,
  brain: PiBrainDuotone,
  dna: PiDnaDuotone,
  eye: PiEyeDuotone,
  feather: PiFeatherDuotone,
  layers: PiStackDuotone,
  lightbulb_filament: PiLightbulbFilamentDuotone,
  number_square_two: PiNumberSquareTwoDuotone,
  puzzle_piece: PiPuzzlePieceDuotone,
  strategy: PiStrategyDuotone,
  timer: PiTimerDuotone,
  tree_structure: PiTreeStructureDuotone,
};
