"use client";

import React from "react";
import {
  Atom,
  Binary,
  Binoculars,
  Bird,
  Blocks,
  Bomb,
  Brush,
  HeartHandshake,
  ThumbsUp,
  MessageCircle,
  Share2,
  Bookmark,
  CircuitBoard,
  Compass,
  Ruler,
  Box,
  Zap,
  Code2,
  PenTool,
  Palette,
  Calculator,
  Users,
  Heart,
  Trophy,
  Medal,
  Target,
  Flame,
  Footprints,
  Sparkles,
  Flag,
  FlagTriangleRight,
  Flower2,
  GitBranch,
  Grid3X3,
  Rocket,
  Bug,
  FlaskConical,
  Cake,
  Star,
  Hash,
  Crown,
  GraduationCap,
  Brain,
  Upload,
  ShieldCheck,
  ShieldPlus,
  LayoutGrid,
  Eye,
  Feather,
  Dna,
  Layers,
  Lightbulb,
  Square,
  Puzzle,
  Swords,
  Timer,
  Network,
} from "lucide-react";

export const PREMIUM_ICONS_MAP: Record<string, React.ElementType> = {
  atom: Atom,
  binary: Binary,
  binoculars: Binoculars,
  bird: Bird,
  blueprint: Blocks,
  bomb: Bomb,
  broom: Brush,
  hand_heart: HeartHandshake,
  thumbs_up: ThumbsUp,
  message_circle: MessageCircle,
  share_2: Share2,
  bookmark: Bookmark,
  circuitry: CircuitBoard,
  compass: Compass,
  compass_tool: Ruler,
  cube: Box,
  zap: Zap,
  code_2: Code2,
  pen_tool: PenTool,
  palette: Palette,
  calculator: Calculator,
  users: Users,
  heart: Heart,
  trophy: Trophy,
  award: Medal,
  target: Target,
  flame: Flame,
  footprints: Footprints,
  sparkles: Sparkles,
  flag: Flag,
  flag_checkered: FlagTriangleRight,
  butterfly: Flower2,
  git_branch: GitBranch,
  grid_nine: Grid3X3,
  rocket: Rocket,
  bug: Bug,
  flask: FlaskConical,
  cake: Cake,
  star: Star,
  hash: Hash,
  crown: Crown,
  graduation_cap: GraduationCap,
  upload: Upload,
  medal: Medal,
  default: Sparkles,
  shield: ShieldCheck,
  shield_star: ShieldPlus,
  "grid_3x3": LayoutGrid,
  brain: Brain,
  dna: Dna,
  eye: Eye,
  feather: Feather,
  layers: Layers,
  lightbulb_filament: Lightbulb,
  number_square_two: Square,
  puzzle_piece: Puzzle,
  strategy: Swords,
  timer: Timer,
  tree_structure: Network,
};
