-- Align fruit cover images with the curated uploaded fruit manifest.
-- Species without a curated fruit/nut image keep their gallery empty and do not point at missing OSS objects.

WITH curated_fruit_covers(slug, cover_image_url) AS (
  VALUES
    ('annona-spp', NULL),
    ('persea-americana', NULL),
    ('cocos-nucifera', NULL),
    ('salacca-edulis', '/fruits/images/salacca-edulis-1.jpg'),
    ('phoenix-dactylifera', NULL),
    ('musa-spp', '/fruits/images/musa-spp-1.jpg'),
    ('ananas-comosus', '/fruits/images/ananas-comosus-1.jpg'),
    ('saccharum-officinarum', NULL),
    ('ribes-spp', NULL),
    ('vitis-vinifera', '/fruits/images/vitis-vinifera-1.jpg'),
    ('tamarindus-indica', NULL),
    ('malus-pumila', '/fruits/images/malus-pumila-1.jpg'),
    ('malus-asiatica', '/fruits/images/malus-asiatica-1.jpg'),
    ('malus-micromalus', NULL),
    ('pyrus-bretschneideri', NULL),
    ('pyrus-ussuriensis', NULL),
    ('pyrus-pyrifolia', '/fruits/images/pyrus-pyrifolia-1.jpg'),
    ('pyrus-communis', NULL),
    ('crataegus-pinnatifida-var-major', NULL),
    ('eriobotrya-japonica', '/fruits/images/eriobotrya-japonica-1.jpg'),
    ('amygdalus-persica', '/fruits/images/amygdalus-persica-1.jpg'),
    ('armeniaca-vulgaris', NULL),
    ('prunus-salicina', '/fruits/images/prunus-salicina-1.jpg'),
    ('prunus-domestica', '/fruits/images/prunus-domestica-1.jpg'),
    ('armeniaca-mume', NULL),
    ('cerasus-pseudocerasus', '/fruits/images/cerasus-pseudocerasus-1.jpg'),
    ('cerasus-avium', NULL),
    ('fragaria-ananassa', NULL),
    ('rubus-spp', NULL),
    ('hippophae-rhamnoides', '/fruits/images/hippophae-rhamnoides-1.jpg'),
    ('ziziphus-jujuba', '/fruits/images/ziziphus-jujuba-1.jpg'),
    ('morus-alba', '/fruits/images/morus-alba-1.jpg'),
    ('ficus-carica', NULL),
    ('artocarpus-heterophyllus', '/fruits/images/artocarpus-heterophyllus-1.jpg'),
    ('myrica-rubra', '/fruits/images/myrica-rubra-1.jpg'),
    ('citrullus-lanatus', NULL),
    ('cucumis-melo', '/fruits/images/cucumis-melo-1.jpg'),
    ('cucumis-metuliferus', '/fruits/images/cucumis-metuliferus-1.jpg'),
    ('siraitia-grosvenorii', NULL),
    ('averrhoa-carambola', '/fruits/images/averrhoa-carambola-1.jpg'),
    ('garcinia-mangostana', '/fruits/images/garcinia-mangostana-1.jpg'),
    ('passiflora-edulis', NULL),
    ('punica-granatum', '/fruits/images/punica-granatum-1.jpg'),
    ('psidium-guajava', '/fruits/images/psidium-guajava-1.jpg'),
    ('syzygium-samarangense', NULL),
    ('canarium-album', NULL),
    ('mangifera-indica', '/fruits/images/mangifera-indica-1.jpg'),
    ('litchi-chinensis', '/fruits/images/litchi-chinensis-1.jpg'),
    ('dimocarpus-longan', '/fruits/images/dimocarpus-longan-1.jpg'),
    ('nephelium-lappaceum', '/fruits/images/nephelium-lappaceum-1.jpg'),
    ('citrus-japonica', '/fruits/images/citrus-japonica-1.jpg'),
    ('citrus-reticulata', NULL),
    ('citrus-maxima', NULL),
    ('citrus-sinensis', '/fruits/images/citrus-sinensis-1.jpg'),
    ('citrus-paradisi', '/fruits/images/citrus-paradisi-1.jpg'),
    ('citrus-limon', NULL),
    ('citrus-aurantiifolia', '/fruits/images/citrus-aurantiifolia-1.jpg'),
    ('citrus-changshan-huyou', '/fruits/images/citrus-changshan-huyou-1.jpg'),
    ('citrus-orah', '/fruits/images/citrus-orah-1.jpg'),
    ('citrus-harumi-shiranui', NULL),
    ('citrus-ehime-28', NULL),
    ('clausena-lansium', NULL),
    ('hibiscus-sabdariffa', '/fruits/images/hibiscus-sabdariffa-1.jpg'),
    ('durio-zibethinus', '/fruits/images/durio-zibethinus-1.jpg'),
    ('carica-papaya', '/fruits/images/carica-papaya-1.jpg'),
    ('hylocereus-undatus', '/fruits/images/hylocereus-undatus-1.jpg'),
    ('diospyros-kaki', '/fruits/images/diospyros-kaki-1.jpg'),
    ('diospyros-lotus', '/fruits/images/diospyros-lotus-1.jpg'),
    ('actinidia-chinensis', '/fruits/images/actinidia-chinensis-1.jpg'),
    ('actinidia-arguta', NULL),
    ('vaccinium-spp', NULL),
    ('vaccinium-spp-cranberry', NULL),
    ('lycopersicon-esculentum', NULL),
    ('solanum-muricatum', '/fruits/images/solanum-muricatum-1.jpg'),
    ('physalis-peruviana', NULL),
    ('lycium-barbarum', NULL),
    ('smallanthus-sonchifolius', '/fruits/images/smallanthus-sonchifolius-1.jpg'),
    ('ginkgo-biloba', NULL),
    ('pinus-koraiensis', NULL),
    ('macadamia-spp', NULL),
    ('arachis-hypogaea', NULL),
    ('amygdalus-communis', '/fruits/images/amygdalus-communis-1.jpg'),
    ('castanea-mollissima', '/fruits/images/castanea-mollissima-1.jpg'),
    ('juglans-regia', NULL),
    ('carya-cathayensis', '/fruits/images/carya-cathayensis-1.jpg'),
    ('carya-illinoinensis', NULL),
    ('corylus-spp', '/fruits/images/corylus-spp-1.jpg'),
    ('cucurbita-spp', '/fruits/images/cucurbita-spp-1.jpg'),
    ('trichosanthes-kirilowii', '/fruits/images/trichosanthes-kirilowii-1.jpg'),
    ('pistacia-vera', '/fruits/images/pistacia-vera-1.jpg'),
    ('anacardium-occidentale', '/fruits/images/anacardium-occidentale-1.jpg'),
    ('helianthus-annuus', NULL)
)
UPDATE public.species AS target
   SET cover_image_url = curated.cover_image_url,
       updated_at = now()
  FROM curated_fruit_covers AS curated
 WHERE target.slug = curated.slug
   AND target.nature_topic = 'plants'
   AND target.plant_uses && ARRAY['fruit', 'nut', 'vegetable', 'edible']::TEXT[]
   AND target.cover_image_url IS DISTINCT FROM curated.cover_image_url;
