-- 统一普通项目与 PBL 的「我的进行中项目」与过程记录。
-- 项目/挑战仍是内容来源；project_journeys 是某个用户的一次尝试；
-- project_journey_records 是私密草稿、公开过程记录或最终作品。

BEGIN;

CREATE TABLE IF NOT EXISTS public.project_journeys (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  source_type text NOT NULL CHECK (source_type IN ('project', 'challenge')),
  project_id bigint REFERENCES public.projects(id) ON DELETE CASCADE,
  challenge_id bigint REFERENCES public.challenges(id) ON DELETE CASCADE,
  title text,
  project_goal text,
  attempt_no integer NOT NULL DEFAULT 1 CHECK (attempt_no > 0),
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'completed', 'abandoned')),
  started_at timestamptz NOT NULL DEFAULT now(),
  last_activity_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT project_journeys_source_check CHECK (
    (source_type = 'project' AND project_id IS NOT NULL AND challenge_id IS NULL)
    OR (source_type = 'challenge' AND challenge_id IS NOT NULL AND project_id IS NULL)
  )
);

CREATE INDEX IF NOT EXISTS idx_project_journeys_user_activity
  ON public.project_journeys (user_id, status, last_activity_at DESC);
CREATE INDEX IF NOT EXISTS idx_project_journeys_project
  ON public.project_journeys (project_id, user_id, status)
  WHERE source_type = 'project';
CREATE INDEX IF NOT EXISTS idx_project_journeys_challenge
  ON public.project_journeys (challenge_id, user_id, status)
  WHERE source_type = 'challenge';
CREATE UNIQUE INDEX IF NOT EXISTS project_journeys_one_active_project
  ON public.project_journeys (user_id, project_id)
  WHERE source_type = 'project' AND project_id IS NOT NULL AND status = 'active';
CREATE UNIQUE INDEX IF NOT EXISTS project_journeys_one_active_challenge
  ON public.project_journeys (user_id, challenge_id)
  WHERE source_type = 'challenge' AND challenge_id IS NOT NULL AND status = 'active';

CREATE TABLE IF NOT EXISTS public.project_journey_records (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  journey_id bigint NOT NULL REFERENCES public.project_journeys(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  record_kind text NOT NULL DEFAULT 'progress' CHECK (record_kind IN ('progress', 'final')),
  anchor_type text NOT NULL DEFAULT 'extra' CHECK (anchor_type IN ('step', 'stage', 'extra', 'final')),
  anchor_index smallint CHECK (anchor_index IS NULL OR anchor_index >= 0),
  title text,
  notes text,
  images text[] NOT NULL DEFAULT '{}'::text[],
  image_captions text[],
  video_url text,
  data jsonb,
  visibility text NOT NULL DEFAULT 'private' CHECK (visibility IN ('private', 'public')),
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'pending', 'approved', 'rejected')),
  moderation_state text NOT NULL DEFAULT 'approved',
  moderation_source text,
  rejection_reason text,
  reviewed_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  reviewed_at timestamptz,
  published_at timestamptz,
  legacy_source text,
  legacy_source_id bigint,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT project_journey_records_kind_anchor_check CHECK (
    (record_kind = 'final' AND anchor_type = 'final')
    OR (record_kind = 'progress' AND anchor_type <> 'final')
  )
);

CREATE INDEX IF NOT EXISTS idx_project_journey_records_journey_time
  ON public.project_journey_records (journey_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_project_journey_records_public
  ON public.project_journey_records (visibility, status, moderation_state, published_at DESC)
  WHERE visibility = 'public';
CREATE INDEX IF NOT EXISTS idx_project_journey_records_legacy
  ON public.project_journey_records (legacy_source, legacy_source_id)
  WHERE legacy_source IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS project_journey_records_one_final
  ON public.project_journey_records (journey_id)
  WHERE record_kind = 'final';
CREATE UNIQUE INDEX IF NOT EXISTS project_journey_records_one_anchored_progress
  ON public.project_journey_records (journey_id, anchor_type, anchor_index)
  WHERE record_kind = 'progress'
    AND anchor_type IN ('step', 'stage')
    AND anchor_index IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS project_journey_records_one_legacy_source
  ON public.project_journey_records (legacy_source, legacy_source_id)
  WHERE legacy_source IS NOT NULL AND legacy_source_id IS NOT NULL;

-- 旧表保留作为兼容投影；新写入逐步通过统一领域服务完成。
ALTER TABLE public.project_explorations
  ADD COLUMN IF NOT EXISTS journey_id bigint REFERENCES public.project_journeys(id) ON DELETE SET NULL;
ALTER TABLE public.completed_projects
  ADD COLUMN IF NOT EXISTS journey_record_id bigint REFERENCES public.project_journey_records(id) ON DELETE SET NULL;
ALTER TABLE public.challenge_workspaces
  ADD COLUMN IF NOT EXISTS journey_id bigint REFERENCES public.project_journeys(id) ON DELETE SET NULL;
ALTER TABLE public.challenge_stage_progress
  ADD COLUMN IF NOT EXISTS journey_id bigint REFERENCES public.project_journeys(id) ON DELETE SET NULL;
ALTER TABLE public.challenge_stage_progress
  ADD COLUMN IF NOT EXISTS journey_record_id bigint REFERENCES public.project_journey_records(id) ON DELETE SET NULL;
ALTER TABLE public.challenge_submissions
  ADD COLUMN IF NOT EXISTS journey_record_id bigint REFERENCES public.project_journey_records(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_project_explorations_journey
  ON public.project_explorations (journey_id)
  WHERE journey_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_completed_projects_journey_record
  ON public.completed_projects (journey_record_id)
  WHERE journey_record_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_challenge_workspaces_journey
  ON public.challenge_workspaces (journey_id)
  WHERE journey_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_challenge_stage_progress_journey_record
  ON public.challenge_stage_progress (journey_record_id)
  WHERE journey_record_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_challenge_stage_progress_journey
  ON public.challenge_stage_progress (journey_id, stage_index)
  WHERE journey_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_challenge_submissions_journey_record
  ON public.challenge_submissions (journey_record_id)
  WHERE journey_record_id IS NOT NULL;

-- Journey 是允许重复尝试的权威模型。旧表继续保留来源级唯一约束，作为兼容投影，
-- 这样尚未切换的旧 API 仍能使用原来的 onConflict 目标；新 Journey 记录不会被它限制。
CREATE UNIQUE INDEX IF NOT EXISTS project_explorations_one_active
  ON public.project_explorations (user_id, project_id)
  WHERE status = 'active';

CREATE UNIQUE INDEX IF NOT EXISTS challenge_stage_progress_one_per_journey_stage
  ON public.challenge_stage_progress (journey_id, stage_index)
  WHERE journey_id IS NOT NULL;

DROP INDEX IF EXISTS public.completed_projects_one_final_per_user_project;
CREATE UNIQUE INDEX IF NOT EXISTS completed_projects_one_legacy_final_per_user_project
  ON public.completed_projects (user_id, project_id)
  WHERE journey_record_id IS NULL AND record_kind = 'final' AND status IN ('pending', 'approved');

ALTER TABLE public.project_journeys ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_journey_records ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.user_owns_project_journey(
  p_journey_id bigint,
  p_user_id uuid
)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT p_user_id = auth.uid()
    AND EXISTS (
      SELECT 1
      FROM public.project_journeys
      WHERE id = p_journey_id AND user_id = p_user_id
    );
$$;

REVOKE ALL ON FUNCTION public.user_owns_project_journey(bigint, uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.user_owns_project_journey(bigint, uuid) TO authenticated;

DROP POLICY IF EXISTS "project_journeys_owner_or_public" ON public.project_journeys;
CREATE POLICY "project_journeys_owner_or_public"
  ON public.project_journeys FOR SELECT
  USING (
    auth.uid() = user_id
    OR EXISTS (
      SELECT 1
      FROM public.profiles
      WHERE id = auth.uid() AND role IN ('admin', 'moderator')
    )
    OR EXISTS (
      SELECT 1
      FROM public.project_journey_records r
      WHERE r.journey_id = project_journeys.id
        AND r.visibility = 'public'
        AND r.status = 'approved'
        AND r.moderation_state = 'approved'
    )
  );

DROP POLICY IF EXISTS "project_journeys_owner_insert" ON public.project_journeys;
CREATE POLICY "project_journeys_owner_insert"
  ON public.project_journeys FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "project_journeys_owner_update" ON public.project_journeys;
CREATE POLICY "project_journeys_owner_update"
  ON public.project_journeys FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "project_journeys_owner_delete" ON public.project_journeys;
CREATE POLICY "project_journeys_owner_delete"
  ON public.project_journeys FOR DELETE
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "project_journey_records_owner_or_public" ON public.project_journey_records;
CREATE POLICY "project_journey_records_owner_or_public"
  ON public.project_journey_records FOR SELECT
  USING (
    auth.uid() = user_id
    OR (
      visibility = 'public'
      AND status = 'approved'
      AND moderation_state = 'approved'
    )
    OR EXISTS (
      SELECT 1
      FROM public.profiles
      WHERE id = auth.uid() AND role IN ('admin', 'moderator')
    )
  );

DROP POLICY IF EXISTS "project_journey_records_owner_insert" ON public.project_journey_records;
CREATE POLICY "project_journey_records_owner_insert"
  ON public.project_journey_records FOR INSERT
  WITH CHECK (public.user_owns_project_journey(journey_id, user_id));

DROP POLICY IF EXISTS "project_journey_records_owner_update" ON public.project_journey_records;
CREATE POLICY "project_journey_records_owner_update"
  ON public.project_journey_records FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (public.user_owns_project_journey(journey_id, user_id));

DROP POLICY IF EXISTS "project_journey_records_owner_delete" ON public.project_journey_records;
CREATE POLICY "project_journey_records_owner_delete"
  ON public.project_journey_records FOR DELETE
  USING (auth.uid() = user_id);

-- 历史回填由迁移事务执行，不代表当前用户提交内容；绕过应用层互动门禁，
-- 迁移结束前恢复触发器。新数据仍由统一 API 和相同门禁保护。
ALTER TABLE public.project_explorations
  DISABLE TRIGGER trg_interaction_access_project_explorations;
ALTER TABLE public.completed_projects
  DISABLE TRIGGER trg_interaction_access_completed_projects;
ALTER TABLE public.challenge_stage_progress
  DISABLE TRIGGER trg_interaction_access_challenge_stage_progress;

-- 旧项目记录有一部分直接写入 completed_projects，没有 exploration_id。
-- 先补一个兼容探索会话，随后再统一映射，避免这些作品脱离新的时间线。
UPDATE public.completed_projects cp
SET exploration_id = e.id
FROM public.project_explorations e
WHERE cp.exploration_id IS NULL
  AND cp.project_id IS NOT NULL
  AND cp.course_lesson_id IS NULL
  AND e.user_id = cp.user_id
  AND e.project_id = cp.project_id;

INSERT INTO public.project_explorations (
  user_id, project_id, status, started_at, last_activity_at, completed_at, created_at, updated_at
)
SELECT
  cp.user_id,
  cp.project_id,
  CASE
    WHEN bool_or(
      COALESCE(cp.record_kind, 'final') = 'final'
      AND cp.status IN ('pending', 'approved')
    ) THEN 'completed'
    ELSE 'active'
  END,
  min(COALESCE(cp.completed_at, now())),
  max(COALESCE(cp.completed_at, now())),
  max(cp.completed_at) FILTER (
    WHERE COALESCE(cp.record_kind, 'final') = 'final'
      AND cp.status IN ('pending', 'approved')
  ),
  min(COALESCE(cp.completed_at, now())),
  max(COALESCE(cp.completed_at, now()))
FROM public.completed_projects cp
WHERE cp.exploration_id IS NULL
  AND cp.project_id IS NOT NULL
  AND cp.course_lesson_id IS NULL
  AND NOT EXISTS (
    SELECT 1
    FROM public.project_explorations e
    WHERE e.user_id = cp.user_id AND e.project_id = cp.project_id
  )
GROUP BY cp.user_id, cp.project_id;

UPDATE public.completed_projects cp
SET exploration_id = e.id
FROM public.project_explorations e
WHERE cp.exploration_id IS NULL
  AND cp.project_id IS NOT NULL
  AND cp.course_lesson_id IS NULL
  AND e.user_id = cp.user_id
  AND e.project_id = cp.project_id;

-- 迁移普通项目探索。
INSERT INTO public.project_journeys (
  user_id, source_type, project_id, title, attempt_no, status,
  started_at, last_activity_at, completed_at, created_at, updated_at
)
SELECT
  e.user_id,
  'project',
  e.project_id,
  p.title,
  1,
  e.status,
  e.started_at,
  e.last_activity_at,
  e.completed_at,
  e.created_at,
  e.updated_at
FROM public.project_explorations e
JOIN public.projects p ON p.id = e.project_id
WHERE e.journey_id IS NULL
  AND NOT EXISTS (
    SELECT 1
    FROM public.project_journeys j
    WHERE j.user_id = e.user_id
      AND j.source_type = 'project'
      AND j.project_id = e.project_id
      AND j.attempt_no = 1
  );

UPDATE public.project_explorations e
SET journey_id = j.id
FROM public.project_journeys j
WHERE e.journey_id IS NULL
  AND j.user_id = e.user_id
  AND j.source_type = 'project'
  AND j.project_id = e.project_id
  AND j.attempt_no = 1;

-- 迁移 PBL 个人工作区。已有工作区仍保留自己的目标与计划。
INSERT INTO public.project_journeys (
  user_id, source_type, challenge_id, title, project_goal, attempt_no, status,
  started_at, last_activity_at, created_at, updated_at
)
SELECT
  w.user_id,
  'challenge',
  w.challenge_id,
  c.title,
  w.project_goal,
  1,
  'active',
  w.created_at,
  w.updated_at,
  w.created_at,
  w.updated_at
FROM public.challenge_workspaces w
JOIN public.challenges c ON c.id = w.challenge_id
WHERE w.journey_id IS NULL
  AND NOT EXISTS (
    SELECT 1
    FROM public.project_journeys j
    WHERE j.user_id = w.user_id
      AND j.source_type = 'challenge'
      AND j.challenge_id = w.challenge_id
      AND j.attempt_no = 1
  );

UPDATE public.challenge_workspaces w
SET journey_id = j.id
FROM public.project_journeys j
WHERE w.journey_id IS NULL
  AND j.user_id = w.user_id
  AND j.source_type = 'challenge'
  AND j.challenge_id = w.challenge_id
  AND j.attempt_no = 1;

UPDATE public.challenge_stage_progress p
SET journey_id = w.journey_id
FROM public.challenge_workspaces w
WHERE p.journey_id IS NULL
  AND w.challenge_id = p.challenge_id
  AND w.user_id = p.user_id
  AND w.journey_id IS NOT NULL;

-- 没有个人工作区但已经写过阶段产出的历史 PBL 参与者，也要拥有一条 Journey。
INSERT INTO public.project_journeys (
  user_id, source_type, challenge_id, title, attempt_no, status,
  started_at, last_activity_at, created_at, updated_at
)
SELECT
  p.user_id,
  'challenge',
  p.challenge_id,
  c.title,
  1,
  'active',
  min(p.created_at),
  max(p.updated_at),
  min(p.created_at),
  max(p.updated_at)
FROM public.challenge_stage_progress p
JOIN public.challenges c ON c.id = p.challenge_id
WHERE p.journey_id IS NULL
  AND NOT EXISTS (
    SELECT 1
    FROM public.project_journeys j
    WHERE j.user_id = p.user_id
      AND j.source_type = 'challenge'
      AND j.challenge_id = p.challenge_id
      AND j.attempt_no = 1
  )
GROUP BY p.user_id, p.challenge_id, c.title;

UPDATE public.challenge_stage_progress p
SET journey_id = j.id
FROM public.project_journeys j
WHERE p.journey_id IS NULL
  AND j.user_id = p.user_id
  AND j.source_type = 'challenge'
  AND j.challenge_id = p.challenge_id
  AND j.attempt_no = 1;

-- 没有工作区、也没有阶段记录但已经提交过挑战作品的历史参与者。
INSERT INTO public.project_journeys (
  user_id, source_type, challenge_id, title, attempt_no, status,
  started_at, last_activity_at, created_at, updated_at
)
SELECT
  s.user_id,
  'challenge',
  s.challenge_id,
  c.title,
  1,
  'active',
  s.created_at,
  s.updated_at,
  s.created_at,
  s.updated_at
FROM public.challenge_submissions s
JOIN public.challenges c ON c.id = s.challenge_id
WHERE NOT EXISTS (
    SELECT 1
    FROM public.project_journeys j
    WHERE j.user_id = s.user_id
      AND j.source_type = 'challenge'
      AND j.challenge_id = s.challenge_id
      AND j.attempt_no = 1
  );

-- 普通项目过程记录/作品回填到统一记录表。
INSERT INTO public.project_journey_records (
  journey_id, user_id, record_kind, anchor_type, title, notes, images,
  image_captions, video_url, visibility, status, moderation_state,
  moderation_source, rejection_reason, reviewed_by, reviewed_at,
  legacy_source, legacy_source_id, created_at, updated_at, published_at
)
SELECT
  legacy.journey_id,
  legacy.user_id,
  CASE
    WHEN COALESCE(legacy.record_kind, 'final') = 'final' AND legacy.final_rank = 1 THEN 'final'
    ELSE 'progress'
  END,
  CASE
    WHEN COALESCE(legacy.record_kind, 'final') = 'final' AND legacy.final_rank = 1 THEN 'final'
    ELSE 'extra'
  END,
  legacy.project_title,
  legacy.notes,
  COALESCE(legacy.proof_images, '{}'::text[]),
  legacy.proof_captions,
  legacy.proof_video_url,
  CASE WHEN COALESCE(legacy.is_public, true) THEN 'public' ELSE 'private' END,
  COALESCE(legacy.status, 'pending'),
  COALESCE(legacy.moderation_state, 'approved'),
  legacy.moderation_source,
  legacy.rejection_reason,
  legacy.reviewed_by,
  legacy.reviewed_at,
  'completed_projects',
  legacy.id,
  COALESCE(legacy.completed_at, now()),
  COALESCE(legacy.completed_at, now()),
  CASE
    WHEN COALESCE(legacy.is_public, true)
      AND COALESCE(legacy.status, 'pending') = 'approved'
      AND COALESCE(legacy.moderation_state, 'approved') = 'approved'
    THEN COALESCE(legacy.completed_at, now())
    ELSE NULL
  END
FROM (
  SELECT
    cp.*,
    e.journey_id,
    p.title AS project_title,
    CASE
      WHEN COALESCE(cp.record_kind, 'final') = 'final' THEN row_number() OVER (
        PARTITION BY e.journey_id
        ORDER BY
          CASE WHEN cp.status = 'approved' THEN 0 WHEN cp.status = 'pending' THEN 1 ELSE 2 END,
          cp.completed_at DESC NULLS LAST,
          cp.id DESC
      )
      ELSE NULL
    END AS final_rank
  FROM public.completed_projects cp
  JOIN public.project_explorations e ON e.id = cp.exploration_id
  JOIN public.projects p ON p.id = cp.project_id
  WHERE cp.project_id IS NOT NULL
    AND cp.course_lesson_id IS NULL
) AS legacy
WHERE legacy.journey_id IS NOT NULL
  AND legacy.journey_record_id IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM public.project_journey_records r
    WHERE r.legacy_source = 'completed_projects' AND r.legacy_source_id = legacy.id
  );

UPDATE public.completed_projects cp
SET journey_record_id = r.id
FROM public.project_journey_records r
WHERE cp.journey_record_id IS NULL
  AND r.legacy_source = 'completed_projects'
  AND r.legacy_source_id = cp.id;

-- PBL 阶段产出成为私密阶段记录，之后由统一发布接口控制公开。
INSERT INTO public.project_journey_records (
  journey_id, user_id, record_kind, anchor_type, anchor_index, notes,
  images, video_url, data, visibility, status, moderation_state,
  legacy_source, legacy_source_id, created_at, updated_at
)
SELECT
  j.id,
  p.user_id,
  'progress',
  'stage',
  p.stage_index,
  p.notes,
  p.images,
  p.video_url,
  p.data,
  'private',
  'draft',
  'approved',
  'challenge_stage_progress',
  p.id,
  p.created_at,
  p.updated_at
FROM public.challenge_stage_progress p
JOIN public.project_journeys j
  ON j.id = p.journey_id
WHERE p.journey_id IS NOT NULL
  AND p.journey_record_id IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM public.project_journey_records r
    WHERE r.legacy_source = 'challenge_stage_progress' AND r.legacy_source_id = p.id
  );

UPDATE public.challenge_stage_progress p
SET journey_record_id = r.id
FROM public.project_journey_records r
WHERE p.journey_record_id IS NULL
  AND r.legacy_source = 'challenge_stage_progress'
  AND r.legacy_source_id = p.id;

-- 挑战作品作为统一最终作品的兼容投影。历史挑战作品仍使用原审核状态。
INSERT INTO public.project_journey_records (
  journey_id, user_id, record_kind, anchor_type, title, notes, images,
  image_captions, video_url, visibility, status, moderation_state,
  rejection_reason, reviewed_by, reviewed_at, legacy_source, legacy_source_id,
  created_at, updated_at, published_at
)
SELECT
  j.id,
  cs.user_id,
  'final',
  'final',
  cs.title,
  cs.notes,
  cs.proof_images,
  cs.proof_captions,
  cs.proof_video_url,
  CASE WHEN cs.is_public THEN 'public' ELSE 'private' END,
  cs.status,
  cs.moderation_state,
  cs.rejection_reason,
  cs.reviewed_by,
  cs.reviewed_at,
  'challenge_submissions',
  cs.id,
  cs.created_at,
  cs.updated_at,
  CASE WHEN cs.is_public AND cs.status = 'approved' THEN cs.updated_at ELSE NULL END
FROM public.challenge_submissions cs
JOIN public.project_journeys j
  ON j.source_type = 'challenge'
 AND j.challenge_id = cs.challenge_id
 AND j.user_id = cs.user_id
 AND j.attempt_no = 1
WHERE j.id IS NOT NULL
  AND cs.journey_record_id IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM public.project_journey_records r
    WHERE r.legacy_source = 'challenge_submissions' AND r.legacy_source_id = cs.id
  );

UPDATE public.challenge_submissions cs
SET journey_record_id = r.id
FROM public.project_journey_records r
WHERE cs.journey_record_id IS NULL
  AND r.legacy_source = 'challenge_submissions'
  AND r.legacy_source_id = cs.id;

UPDATE public.project_journeys j
SET status = 'completed', completed_at = COALESCE(j.completed_at, r.updated_at), updated_at = now()
FROM public.project_journey_records r
WHERE r.journey_id = j.id
  AND r.record_kind = 'final'
  AND r.visibility = 'public'
  AND r.status = 'approved'
  AND r.moderation_state = 'approved'
  AND j.status = 'active';

ALTER TABLE public.project_explorations
  ENABLE TRIGGER trg_interaction_access_project_explorations;
ALTER TABLE public.completed_projects
  ENABLE TRIGGER trg_interaction_access_completed_projects;
ALTER TABLE public.challenge_stage_progress
  ENABLE TRIGGER trg_interaction_access_challenge_stage_progress;

COMMIT;
