-- 探索会话 + 过程帖/终稿 + AI 审核日志

-- ============================================
-- 1. project_explorations
-- ============================================

CREATE TABLE IF NOT EXISTS public.project_explorations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    project_id bigint NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    status text NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'completed', 'abandoned')),
    started_at timestamptz NOT NULL DEFAULT now(),
    last_activity_at timestamptz NOT NULL DEFAULT now(),
    completed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (user_id, project_id)
);

CREATE INDEX IF NOT EXISTS idx_project_explorations_user_status
    ON public.project_explorations (user_id, status);

CREATE INDEX IF NOT EXISTS idx_project_explorations_project_status
    ON public.project_explorations (project_id, status);

ALTER TABLE public.project_explorations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users manage own explorations" ON public.project_explorations;
CREATE POLICY "Users manage own explorations"
    ON public.project_explorations
    FOR ALL
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Public read explorations for approved feed context" ON public.project_explorations;
CREATE POLICY "Explorations readable by owner"
    ON public.project_explorations
    FOR SELECT
    USING (auth.uid() = user_id OR public.is_moderator_or_admin());

COMMENT ON TABLE public.project_explorations IS '用户在某项目上的探索会话（开始探索 / 交终稿后完成）';

-- ============================================
-- 2. completed_projects 扩展
-- ============================================

ALTER TABLE public.completed_projects
    ADD COLUMN IF NOT EXISTS record_kind text NOT NULL DEFAULT 'final';

ALTER TABLE public.completed_projects
    ADD COLUMN IF NOT EXISTS record_type text;

ALTER TABLE public.completed_projects
    ADD COLUMN IF NOT EXISTS stage_label text;

ALTER TABLE public.completed_projects
    ADD COLUMN IF NOT EXISTS exploration_id bigint REFERENCES public.project_explorations(id) ON DELETE SET NULL;

ALTER TABLE public.completed_projects
    ADD COLUMN IF NOT EXISTS moderation_source text;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'completed_projects_record_kind_check'
    ) THEN
        ALTER TABLE public.completed_projects
            ADD CONSTRAINT completed_projects_record_kind_check
            CHECK (record_kind IN ('progress', 'final'));
    END IF;
END $$;

UPDATE public.completed_projects
SET record_kind = 'final'
WHERE record_kind IS NULL OR record_kind = '';

CREATE INDEX IF NOT EXISTS idx_completed_projects_record_kind
    ON public.completed_projects (project_id, record_kind, status, completed_at DESC);

-- 每用户每项目至多一条进行中的终稿（pending/approved）
CREATE UNIQUE INDEX IF NOT EXISTS completed_projects_one_final_per_user_project
    ON public.completed_projects (user_id, project_id)
    WHERE record_kind = 'final' AND status IN ('pending', 'approved');

-- ============================================
-- 3. completion_moderation_logs
-- ============================================

CREATE TABLE IF NOT EXISTS public.completion_moderation_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    completion_id bigint NOT NULL REFERENCES public.completed_projects(id) ON DELETE CASCADE,
    status text NOT NULL DEFAULT 'queued'
        CHECK (status IN ('queued', 'running', 'done', 'error')),
    moderation_pass boolean,
    moderation_reason text,
    raw_response jsonb,
    error_message text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (completion_id)
);

CREATE INDEX IF NOT EXISTS idx_completion_moderation_logs_status
    ON public.completion_moderation_logs (status, updated_at);

ALTER TABLE public.completion_moderation_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Moderation logs owner or admin" ON public.completion_moderation_logs;
CREATE POLICY "Moderation logs owner or admin"
    ON public.completion_moderation_logs
    FOR SELECT
    USING (
        public.is_moderator_or_admin()
        OR EXISTS (
            SELECT 1 FROM public.completed_projects cp
            WHERE cp.id = completion_id AND cp.user_id = auth.uid()
        )
    );

DROP POLICY IF EXISTS "Service role manages moderation logs" ON public.completion_moderation_logs;
CREATE POLICY "Service role manages moderation logs"
    ON public.completion_moderation_logs
    FOR ALL
    USING (auth.role() = 'service_role')
    WITH CHECK (auth.role() = 'service_role');

-- ============================================
-- 4. 系统审核 RPC（供 Worker / service_role）
-- ============================================

CREATE OR REPLACE FUNCTION public.system_approve_completion(p_completion_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    UPDATE public.completed_projects
    SET
        status = 'approved',
        reviewed_at = now(),
        reviewed_by = NULL,
        rejection_reason = NULL,
        moderation_source = COALESCE(moderation_source, 'ai')
    WHERE id = p_completion_id
      AND status = 'pending';

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Completion % not found or not pending', p_completion_id;
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.system_reject_completion(
    p_completion_id bigint,
    p_reason text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    UPDATE public.completed_projects
    SET
        status = 'rejected',
        reviewed_at = now(),
        reviewed_by = NULL,
        rejection_reason = COALESCE(NULLIF(trim(p_reason), ''), '内容未通过审核'),
        moderation_source = COALESCE(moderation_source, 'ai')
    WHERE id = p_completion_id
      AND status = 'pending';

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Completion % not found or not pending', p_completion_id;
    END IF;
END;
$$;

REVOKE ALL ON FUNCTION public.system_approve_completion(bigint) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.system_reject_completion(bigint, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.system_approve_completion(bigint) TO service_role;
GRANT EXECUTE ON FUNCTION public.system_reject_completion(bigint, text) TO service_role;

COMMENT ON FUNCTION public.system_approve_completion IS 'AI/系统 Worker 批准作品（无需审核员角色）';
COMMENT ON FUNCTION public.system_reject_completion IS 'AI/系统 Worker 拒绝作品';
